package CalcApp;


/**
* CalcApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Wednesday, 15 April, 2026 1:04:54 AM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  float divide (float a, float b);
} // interface CalculatorOperations
